# Generated by Django 5.1.2 on 2024-11-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=120)),
                ('url', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('category', models.CharField(choices=[('nature', 'Nature'), ('architecture', 'Architecture'), ('portrait', 'Portrait'), ('bets', 'Bets'), ('aerial', 'Aerial')], max_length=15)),
                ('location', models.CharField(default='Jeddah', max_length=30)),
                ('captured_at', models.DateField()),
            ],
        ),
    ]
