# Generated by Django 5.1.2 on 2024-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0002_remove_photo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(default='Jeddah', max_length=30),
        ),
    ]
