# Generated by Django 5.1.2 on 2024-11-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0003_photo_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='location',
            new_name='photo_location',
        ),
    ]
