# Generated by Django 5.1.2 on 2024-11-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryApp', '0004_rename_location_photo_photo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_location',
            field=models.CharField(max_length=30),
        ),
    ]
