# Generated by Django 5.1.2 on 2024-11-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_techstack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
                ('progress', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='techstack',
            old_name='skill',
            new_name='tool',
        ),
    ]
