# Generated by Django 5.1.2 on 2024-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Photo Session', 'Photo Session'), ('Preset Filter', 'Preset Filter'), ('Programming Project', 'Programming Project'), ('Consultant', 'Consultant')], max_length=50)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='products/')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
