# Generated by Django 5.1.2 on 2024-11-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='client_email',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='client_name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='request',
            name='client_note',
            field=models.TextField(default='none'),
        ),
    ]
