# Generated by Django 5.1.2 on 2024-11-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0004_request_client_email_request_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('Preset Filter', 'Preset Filter'), ('Photo Session', 'Photo Session'), ('Programming Project', 'Programming Project'), ('Consultant', 'Consultant')], max_length=50),
        ),
    ]
